# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookViewSet 

# Initialize the Router
# The router automatically generates all required URL patterns for the ViewSet.
router = DefaultRouter()

# Register the BookViewSet with the router.
# The endpoint will be accessed via the path 'books/' (e.g., /api/books/)
router.register(r'books', BookViewSet)

# The urlpatterns now includes all the URLs generated by the router.
urlpatterns = [
    # Include the router's URLs under the root path of the app
    path('', include(router.urls)),
]