
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookList, BookViewSet 

# 1. Initialize the Router and register the ViewSet
router = DefaultRouter()
# Register the BookViewSet under the base name 'books_all'
router.register(r'books_all', BookViewSet, basename='book_all')

# 2. Define urlpatterns to include both explicit path and router URLs
urlpatterns = [
    # Route 1: The explicit path for the existing ListAPIView (Read-Only)
    path('books/', BookList.as_view(), name='book-list'),
    
    # Route 2: Include all URLs automatically generated by the router for BookViewSet (Full CRUD)
    path('', include(router.urls)),
]